/* ==========================================================================
   FinPulse AI - Application Logic & Interactive Engines
   ========================================================================== */

document.addEventListener('DOMContentLoaded', () => {

    // --- State Management ---
    const appState = {
        xp: 1450,
        streak: 5,
        currentTab: 'bs-detector',
        currentStrategy: 'balanced',
        isCrashSimulated: false,
        salary: 28000,
        pensionPct: 5,
        monthlyDeposit: 150
    };

    // --- 1. Tab Navigation ---
    const navButtons = document.querySelectorAll('.nav-btn');
    const tabContents = document.querySelectorAll('.tab-content');

    navButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            const targetTab = btn.getAttribute('data-tab');
            
            navButtons.forEach(b => b.classList.remove('active'));
            tabContents.forEach(tc => tc.classList.remove('active'));

            btn.classList.add('active');
            const targetContent = document.getElementById(targetTab);
            if (targetContent) {
                targetContent.classList.add('active');
            }

            if (targetTab === 'investment-sandbox') {
                renderGrowthChart();
            }
        });
    });

    // --- 2. TikTok / Finfluencer BS Scanner ---
    const presetData = {
        forex: {
            text: "Bro, just put £500 into this new forex signals group with 100x leverage! Made £5,000 yesterday while sleeping. DM me for the private VIP link 💸🚀",
            score: "96%",
            risk: "Extreme Leverage (100x)",
            monetization: "Affiliate Broker Commission",
            flags: [
                "100x leverage multiplies losses so a 1% dip wipes out 100% of your money instantly.",
                "The creator earns money from broker affiliate links when you lose your deposit.",
                "Unregulated offshore broker — no FCA protection or FSCS guarantee."
            ],
            reality: "FCA data shows 82% of retail traders using forex leverage lose their entire initial deposit within 30 days. Real wealth comes from low-cost index compounding, not signal groups.",
            verdict: "DO NOT FOLLOW THIS ADVICE. High risk of complete capital destruction."
        },
        crypto: {
            text: "This new low-cap meme token is launching on DEX today! Guaranteed 100x gains before liquidity lock. Buy now or cry later! 💎🙌",
            score: "91%",
            risk: "Rug-Pull / Liquidity Drain",
            monetization: "Creator Token Allocation Dump",
            flags: [
                "Unverified smart contract code — risk of honeypot where selling is disabled.",
                "High creator token concentration: developers can dump holdings and drain liquidity pool.",
                "Fake hype generated by paid bot accounts on X and Telegram."
            ],
            reality: "Over 97% of DEX meme tokens launched daily become inactive or worthless within 14 days. Treat crypto sandbox trading as high-risk speculation.",
            verdict: "HIGH RISK SPECULATION. Only gamble money you are 100% prepared to write off."
        },
        bnpl: {
            text: "Why pay £120 for clothes today when you can split it into 4 easy interest-free payments? It's basically free money and doesn't affect anything! 🛍️✨",
            score: "65%",
            risk: "Debt Stacking & Credit Damage",
            monetization: "Merchant Fees + Late Payment Penalties",
            flags: [
                "BNPL services encourage impulsive 'micro-debt' stacking across multiple apps.",
                "Missing payments triggers missed payment markers reported to UK Credit Reference Agencies.",
                "Can severely impact your future mortgage or tenancy application suitability."
            ],
            reality: "BNPL is a credit product, not free money. Missing a £15 payment can harm your ability to rent an apartment 2 years later.",
            verdict: "USE WITH CAUTION. Track all installments as real debt commitments."
        },
        index: {
            text: "Invest £150 a month into a low-cost, broadly diversified Global Index ETF (like S&P 500 or FTSE All-World) and let compound growth build long-term wealth over 10+ years.",
            score: "12%",
            risk: "Normal Market Volatility",
            monetization: "Low ETF Management Fee (0.07%)",
            flags: [
                "Short-term price fluctuations will occur during market dips.",
                "Requires long-term patience (5-10+ year time horizon)."
            ],
            reality: "Historically, broad market index funds have delivered ~7-10% annualized returns over multi-decade periods with zero reliance on timing the market.",
            verdict: "SOLID FINANCIAL EDUCATION PRACTICE. Encourages investor mindset over gambling."
        }
    };

    const platformChips = document.querySelectorAll('.platform-chip');
    const presetChips = document.querySelectorAll('.preset-chip');
    const claimInput = document.getElementById('claim-input');
    const scanBtn = document.getElementById('scan-btn');

    platformChips.forEach(chip => {
        chip.addEventListener('click', () => {
            platformChips.forEach(c => c.classList.remove('active'));
            chip.classList.add('active');
        });
    });

    presetChips.forEach(chip => {
        chip.addEventListener('click', () => {
            presetChips.forEach(c => c.classList.remove('active'));
            chip.classList.add('active');
            const key = chip.getAttribute('data-preset');
            if (presetData[key]) {
                claimInput.value = presetData[key].text;
                runBSScan(presetData[key]);
            }
        });
    });

    // Set initial preset
    claimInput.value = presetData.forex.text;

    scanBtn.addEventListener('click', () => {
        const text = claimInput.value.toLowerCase();
        let matched = presetData.forex;
        if (text.includes('index') || text.includes('etf') || text.includes('s&p')) {
            matched = presetData.index;
        } else if (text.includes('bnpl') || text.includes('pay later') || text.includes('split')) {
            matched = presetData.bnpl;
        } else if (text.includes('crypto') || text.includes('coin') || text.includes('token')) {
            matched = presetData.crypto;
        }
        runBSScan(matched);
    });

    function runBSScan(data) {
        document.getElementById('metric-score').innerText = data.score;
        document.getElementById('metric-risk').innerText = data.risk;
        document.getElementById('metric-monetization').innerText = data.monetization;
        
        const flagsList = document.getElementById('red-flags-list');
        flagsList.innerHTML = '';
        data.flags.forEach(f => {
            const li = document.createElement('li');
            li.innerText = f;
            flagsList.appendChild(li);
        });

        document.getElementById('reality-text').innerText = data.reality;
        document.getElementById('verdict-banner').querySelector('span').innerText = data.verdict;

        const badge = document.getElementById('risk-badge');
        if (parseInt(data.score) > 60) {
            badge.className = 'risk-badge risk-high';
            badge.innerHTML = '<i class="fa-solid fa-triangle-exclamation"></i> HIGH RISK / RED FLAGS DETECTED';
            document.getElementById('metric-score').className = 'metric-val text-red';
        } else {
            badge.className = 'risk-badge risk-low';
            badge.innerHTML = '<i class="fa-solid fa-circle-check"></i> LOW RISK / VERIFIED EDUCATIONAL PATTERN';
            document.getElementById('metric-score').className = 'metric-val text-green';
        }
    }

    // --- 3. UK Payslip Calculator Engine ---
    const salarySlider = document.getElementById('salary-slider');
    const salaryDisplay = document.getElementById('salary-display');
    const taxCodeSelect = document.getElementById('tax-code-select');
    const studentLoanSelect = document.getElementById('student-loan-select');
    const pensionSlider = document.getElementById('pension-slider');
    const pensionDisplay = document.getElementById('pension-display');

    function updatePayslip() {
        const salary = parseFloat(salarySlider.value);
        appState.salary = salary;
        salaryDisplay.innerText = `£${salary.toLocaleString()} / year`;

        const taxCode = taxCodeSelect.value;
        const studentLoan = studentLoanSelect.value;
        const pensionPct = parseFloat(pensionSlider.value);
        appState.pensionPct = pensionPct;

        pensionDisplay.innerText = `${pensionPct}% (Employee) + 3% (Employer)`;
        document.getElementById('ps-tax-code').innerText = taxCode;

        // Gross Monthly
        const grossMonthly = salary / 12;

        // Personal Allowance
        let personalAllowance = 12570;
        if (taxCode === 'BR') personalAllowance = 0;

        const monthlyAllowance = personalAllowance / 12;
        const taxableMonthly = Math.max(0, grossMonthly - monthlyAllowance);

        // PAYE Tax (Basic rate 20% for simplicity up to £50k)
        const payeMonthly = taxableMonthly * 0.20;

        // National Insurance (UK 2026: 8% between £12,570 and £50,270)
        const niThresholdMonthly = 12570 / 12;
        const niTaxableMonthly = Math.max(0, grossMonthly - niThresholdMonthly);
        const niMonthly = niTaxableMonthly * 0.08;

        // Pension
        const pensionMonthly = grossMonthly * (pensionPct / 100);
        const employerPensionMonthly = grossMonthly * 0.03;

        // Student Loan
        let studentLoanMonthly = 0;
        if (studentLoan === 'plan2' && salary > 27295) {
            studentLoanMonthly = ((salary - 27295) * 0.09) / 12;
        } else if (studentLoan === 'plan5' && salary > 25000) {
            studentLoanMonthly = ((salary - 25000) * 0.09) / 12;
        }

        const totalDeductions = payeMonthly + niMonthly + pensionMonthly + studentLoanMonthly;
        const netTakeHome = grossMonthly - totalDeductions;

        // Update DOM
        document.getElementById('ps-gross').innerText = `£${grossMonthly.toFixed(2)}`;
        document.getElementById('ps-tax').innerText = `-£${payeMonthly.toFixed(2)}`;
        document.getElementById('ps-ni').innerText = `-£${niMonthly.toFixed(2)}`;
        document.getElementById('ps-pension').innerText = `-£${pensionMonthly.toFixed(2)}`;
        document.getElementById('ps-student-loan').innerText = `-£${studentLoanMonthly.toFixed(2)}`;
        document.getElementById('ps-total-deductions').innerText = `£${totalDeductions.toFixed(2)}`;
        document.getElementById('ps-net-pay').innerText = `£${netTakeHome.toFixed(2)}`;

        document.getElementById('payslip-tip').innerHTML = `Your employer adds an extra <strong>£${employerPensionMonthly.toFixed(2)}/mo FREE money</strong> to your workplace pension! Never opt out of your match.`;
    }

    salarySlider.addEventListener('input', updatePayslip);
    taxCodeSelect.addEventListener('change', updatePayslip);
    studentLoanSelect.addEventListener('change', updatePayslip);
    pensionSlider.addEventListener('input', updatePayslip);

    updatePayslip(); // initial calculation

    // --- 4. Investor vs Gambler Growth Simulator & Canvas ---
    const depositSlider = document.getElementById('deposit-slider');
    const depositDisplay = document.getElementById('deposit-display');
    const strategyCards = document.querySelectorAll('.strategy-card');
    const simulateCrashBtn = document.getElementById('simulate-crash-btn');

    depositSlider.addEventListener('input', () => {
        appState.monthlyDeposit = parseFloat(depositSlider.value);
        depositDisplay.innerText = `£${appState.monthlyDeposit} / month`;
        renderGrowthChart();
    });

    strategyCards.forEach(card => {
        card.addEventListener('click', () => {
            strategyCards.forEach(c => c.classList.remove('active'));
            card.classList.add('active');
            appState.currentStrategy = card.getAttribute('data-strategy');
            appState.isCrashSimulated = false;
            renderGrowthChart();
        });
    });

    simulateCrashBtn.addEventListener('click', () => {
        appState.isCrashSimulated = true;
        renderGrowthChart();
    });

    function renderGrowthChart() {
        const canvas = document.getElementById('growthCanvas');
        if (!canvas) return;
        const ctx = canvas.getContext('2d');
        const width = canvas.width;
        const height = canvas.height;

        ctx.clearRect(0, 0, width, height);

        const monthly = appState.monthlyDeposit;
        const months = 60; // 5 years

        let rates = []; // monthly growth multipliers
        let dataPoints = [0];
        let totalInvestedPoints = [0];

        let annualRate = 0.08;
        if (appState.currentStrategy === 'savings') annualRate = 0.045;
        if (appState.currentStrategy === 'gambler') annualRate = 0.25;

        const monthlyRate = annualRate / 12;

        let currentVal = 0;
        let cumulativeInvested = 0;

        for (let m = 1; m <= months; m++) {
            cumulativeInvested += monthly;
            totalInvestedPoints.push(cumulativeInvested);

            currentVal = (currentVal + monthly) * (1 + monthlyRate);

            // If crash simulated at month 30
            if (appState.isCrashSimulated && m === 30) {
                if (appState.currentStrategy === 'gambler') {
                    currentVal *= 0.20; // 80% drop in meme crypto
                } else if (appState.currentStrategy === 'balanced') {
                    currentVal *= 0.75; // 25% drop market correction
                }
            }

            dataPoints.push(currentVal);
        }

        const finalVal = dataPoints[months];
        const finalInvested = totalInvestedPoints[months];
        const gain = finalVal - finalInvested;
        const gainPct = ((gain / finalInvested) * 100).toFixed(1);

        document.getElementById('sum-invested').innerText = `£${finalInvested.toLocaleString()}`;
        document.getElementById('sum-projected').innerText = `£${Math.round(finalVal).toLocaleString()}`;
        document.getElementById('sum-gain').innerText = `${gain >= 0 ? '+' : ''}£${Math.round(gain).toLocaleString()} (${gainPct}%)`;

        const badge = document.getElementById('chart-badge');
        const lessonTitle = document.getElementById('lesson-title');
        const lessonBody = document.getElementById('lesson-body');

        if (appState.currentStrategy === 'balanced') {
            badge.className = 'badge badge-green';
            badge.innerText = 'Smart Index Investor';
            lessonTitle.innerText = 'The Power of Compound Interest';
            lessonBody.innerText = 'Starting with just £' + monthly + '/month at age 20 creates exponential compounding. Time in the market beats timing the market!';
        } else if (appState.currentStrategy === 'gambler') {
            badge.className = 'badge risk-high';
            badge.innerText = 'High Risk Meme/Gambling';
            lessonTitle.innerText = 'Extreme Volatility & Drawdown Risk';
            lessonBody.innerText = 'High-leverage and meme trading can produce temporary spikes, but massive drawdowns destroy long-term compound growth.';
        } else {
            badge.className = 'badge badge-purple';
            badge.innerText = 'Cash Savings Account';
            lessonTitle.innerText = 'Safety vs Inflation Risk';
            lessonBody.innerText = 'Cash savings is 100% safe, but after 5 years, real purchasing power drops if inflation exceeds your interest rate.';
        }

        // Draw Canvas Grid & Lines
        const padding = 40;
        const chartWidth = width - padding * 2;
        const chartHeight = height - padding * 2;

        const maxVal = Math.max(...dataPoints, ...totalInvestedPoints) * 1.1;

        // Draw Grid Lines
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.08)';
        ctx.lineWidth = 1;
        for (let i = 0; i <= 4; i++) {
            const y = height - padding - (chartHeight / 4) * i;
            ctx.beginPath();
            ctx.moveTo(padding, y);
            ctx.lineTo(width - padding, y);
            ctx.stroke();
        }

        // Draw Total Invested Line (Baseline)
        ctx.beginPath();
        ctx.strokeStyle = '#6b7280';
        ctx.lineWidth = 2;
        ctx.setLineDash([5, 5]);
        for (let m = 0; m <= months; m++) {
            const x = padding + (chartWidth / months) * m;
            const y = height - padding - (totalInvestedPoints[m] / maxVal) * chartHeight;
            if (m === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        }
        ctx.stroke();
        ctx.setLineDash([]);

        // Draw Growth Trajectory Line
        ctx.beginPath();
        ctx.strokeStyle = appState.currentStrategy === 'gambler' ? '#ef4444' : '#10b981';
        ctx.lineWidth = 3;
        for (let m = 0; m <= months; m++) {
            const x = padding + (chartWidth / months) * m;
            const y = height - padding - (dataPoints[m] / maxVal) * chartHeight;
            if (m === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        }
        ctx.stroke();
    }

    // --- 5. Gamified Quests & Quiz Modal ---
    const startQuizBtn = document.getElementById('start-quiz-btn');
    const quizModal = document.getElementById('quiz-modal');
    const closeQuizBtn = document.getElementById('close-quiz-btn');
    const quizOptBtns = document.querySelectorAll('.quiz-opt-btn');
    const quizFeedback = document.getElementById('quiz-feedback');

    if (startQuizBtn) {
        startQuizBtn.addEventListener('click', () => {
            quizModal.classList.remove('hidden');
            quizFeedback.classList.add('hidden');
        });
    }

    if (closeQuizBtn) {
        closeQuizBtn.addEventListener('click', () => {
            quizModal.classList.add('hidden');
        });
    }

    quizOptBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const isCorrect = btn.getAttribute('data-correct') === 'true';
            quizFeedback.classList.remove('hidden');
            if (isCorrect) {
                appState.xp += 150;
                document.getElementById('xp-count').innerText = `${appState.xp.toLocaleString()} XP`;
            }
        });
    });
});
